---
dist: trusty
services:
  - docker
  - redis
language: go
matrix:
  include:
    - go: "1.8"
    - go: "1.9"
    - go: "1.10"
      env: COVERAGE=true

before_install:
  - docker run -d -p 5984:5984 --net=host --name couch apache/couchdb:2.1

before_script:
  - curl -X PUT http://127.0.0.1:5984/{_users,_replicator,_global_changes}
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - gometalinter --config=.golinter ./...
  - ./scripts/no-forbidden-packages.sh

script:
  - if [[ "$COVERAGE" == "true" ]]; then
      ./scripts/coverage.sh;
    else
      go test -timeout 2m ./...;
    fi

after_success:
  - if [[ "$COVERAGE" == "true" ]]; then
      bash <(curl -s https://codecov.io/bash);
    fi

after_failure:
  - docker ps -a
