---
dist: trusty
services:
  - docker
  - redis
language: go
go:
  - "1.8"
  - "1.9"
  - "1.10"

before_install:
  - docker run -d -p 5984:5984 --net=host --name couch apache/couchdb:2.1

before_script:
  - curl -X PUT http://127.0.0.1:5984/{_users,_replicator,_global_changes}
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - gometalinter --config=.golinter ./...
  - ./scripts/no-forbidden-packages.sh

script:
  - ./scripts/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - docker ps -a
