name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      couchdb:
        image: apache/couchdb:2.3
        ports:
          - 5984:5984
      redis:
        image: redis
        ports:
          - 6379:6379
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install
        run: |
          git config --global user.email "github@spam.cozycloud.cc"
          git config --global user.name "github actions"
          curl -X PUT http://127.0.0.1:5984/{_users,_replicator,_global_changes}
          echo ::add-path::$(go env GOPATH)/bin
          go install
      - name: Lint
        if: matrix.go-version == '1.13.x'
        run: ./scripts/lint.sh
      - name: Unit tests
        run: go test -timeout 2m ./...
