name: Build docs and shell completions
on:
  push:
    branches:
      - master
    paths:
      - 'cmd/*.go'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: Install
        run: |
          echo ::add-path::$(go env GOPATH)/bin
          go install
      - name: Build
        run: |
          rm -rf docs/cli/*
          cozy-stack doc markdown docs/cli
          cozy-stack completion bash > scripts/completion/cozy-stack.bash
          cozy-stack completion zsh > scripts/completion/cozy-stack.zsh
          git diff
      - uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Build CLI docs and shell completions
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
