name: Integration tests
on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      couchdb:
        image: apache/couchdb:2.3
        ports:
          - 5984:5984
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: Install
        run: |
          curl -X PUT http://127.0.0.1:5984/{_users,_replicator,_global_changes}
          echo ::add-path::$(go env GOPATH)/bin
          go install
      - name: Test
        run: ./scripts/integration-test.sh
